language: cpp

compiler:
  - gcc-4.8

#sudo: false

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-4.8
#    - g++-4.8
#    - libboost-dev
before_install:
  # pyparsing
  - sudo easy_install pyparsing
  - sudo apt-get install cmake
install:
  
before_script:

script:
  - ./test_with_JsonCPP.sh
  - ./test_with_RapidJson.sh

notifications:
  email: false
  
os:
  - linux
  # - osx